
export type ElementData = {
  name: string;
  atomicNumber: number;
  symbol: string;
  atomicMass: number;
  group: number;
  period: number;
  category: 'alkali-metal' | 'alkaline-earth-metal' | 'lanthanide' | 'actinide' | 'transition-metal' | 'post-transition-metal' | 'metalloid' | 'reactive-nonmetal' | 'noble-gas' | 'unknown';
};

export const elements: ElementData[] = [
  { name: 'Hydrogen', atomicNumber: 1, symbol: 'H', atomicMass: 1.008, group: 1, period: 1, category: 'reactive-nonmetal' },
  { name: 'Helium', atomicNumber: 2, symbol: 'He', atomicMass: 4.0026, group: 18, period: 1, category: 'noble-gas' },
  { name: 'Lithium', atomicNumber: 3, symbol: 'Li', atomicMass: 6.94, group: 1, period: 2, category: 'alkali-metal' },
  { name: 'Beryllium', atomicNumber: 4, symbol: 'Be', atomicMass: 9.0122, group: 2, period: 2, category: 'alkaline-earth-metal' },
  { name: 'Boron', atomicNumber: 5, symbol: 'B', atomicMass: 10.81, group: 13, period: 2, category: 'metalloid' },
  { name: 'Carbon', atomicNumber: 6, symbol: 'C', atomicMass: 12.011, group: 14, period: 2, category: 'reactive-nonmetal' },
  { name: 'Nitrogen', atomicNumber: 7, symbol: 'N', atomicMass: 14.007, group: 15, period: 2, category: 'reactive-nonmetal' },
  { name: 'Oxygen', atomicNumber: 8, symbol: 'O', atomicMass: 15.999, group: 16, period: 2, category: 'reactive-nonmetal' },
  { name: 'Fluorine', atomicNumber: 9, symbol: 'F', atomicMass: 18.998, group: 17, period: 2, category: 'reactive-nonmetal' },
  { name: 'Neon', atomicNumber: 10, symbol: 'Ne', atomicMass: 20.180, group: 18, period: 2, category: 'noble-gas' },
  { name: 'Sodium', atomicNumber: 11, symbol: 'Na', atomicMass: 22.990, group: 1, period: 3, category: 'alkali-metal' },
  { name: 'Magnesium', atomicNumber: 12, symbol: 'Mg', atomicMass: 24.305, group: 2, period: 3, category: 'alkaline-earth-metal' },
  { name: 'Aluminium', atomicNumber: 13, symbol: 'Al', atomicMass: 26.982, group: 13, period: 3, category: 'post-transition-metal' },
  { name: 'Silicon', atomicNumber: 14, symbol: 'Si', atomicMass: 28.085, group: 14, period: 3, category: 'metalloid' },
  { name: 'Phosphorus', atomicNumber: 15, symbol: 'P', atomicMass: 30.974, group: 15, period: 3, category: 'reactive-nonmetal' },
  { name: 'Sulfur', atomicNumber: 16, symbol: 'S', atomicMass: 32.06, group: 16, period: 3, category: 'reactive-nonmetal' },
  { name: 'Chlorine', atomicNumber: 17, symbol: 'Cl', atomicMass: 35.45, group: 17, period: 3, category: 'reactive-nonmetal' },
  { name: 'Argon', atomicNumber: 18, symbol: 'Ar', atomicMass: 39.948, group: 18, period: 3, category: 'noble-gas' },
  { name: 'Potassium', atomicNumber: 19, symbol: 'K', atomicMass: 39.098, group: 1, period: 4, category: 'alkali-metal' },
  { name: 'Calcium', atomicNumber: 20, symbol: 'Ca', atomicMass: 40.078, group: 2, period: 4, category: 'alkaline-earth-metal' },
  { name: 'Scandium', atomicNumber: 21, symbol: 'Sc', atomicMass: 44.956, group: 3, period: 4, category: 'transition-metal' },
  { name: 'Titanium', atomicNumber: 22, symbol: 'Ti', atomicMass: 47.867, group: 4, period: 4, category: 'transition-metal' },
  { name: 'Vanadium', atomicNumber: 23, symbol: 'V', atomicMass: 50.942, group: 5, period: 4, category: 'transition-metal' },
  { name: 'Chromium', atomicNumber: 24, symbol: 'Cr', atomicMass: 51.996, group: 6, period: 4, category: 'transition-metal' },
  { name: 'Manganese', atomicNumber: 25, symbol: 'Mn', atomicMass: 54.938, group: 7, period: 4, category: 'transition-metal' },
  { name: 'Iron', atomicNumber: 26, symbol: 'Fe', atomicMass: 55.845, group: 8, period: 4, category: 'transition-metal' },
  { name: 'Cobalt', atomicNumber: 27, symbol: 'Co', atomicMass: 58.933, group: 9, period: 4, category: 'transition-metal' },
  { name: 'Nickel', atomicNumber: 28, symbol: 'Ni', atomicMass: 58.693, group: 10, period: 4, category: 'transition-metal' },
  { name: 'Copper', atomicNumber: 29, symbol: 'Cu', atomicMass: 63.546, group: 11, period: 4, category: 'transition-metal' },
  { name: 'Zinc', atomicNumber: 30, symbol: 'Zn', atomicMass: 65.38, group: 12, period: 4, category: 'transition-metal' },
  { name: 'Gallium', atomicNumber: 31, symbol: 'Ga', atomicMass: 69.723, group: 13, period: 4, category: 'post-transition-metal' },
  { name: 'Germanium', atomicNumber: 32, symbol: 'Ge', atomicMass: 72.63, group: 14, period: 4, category: 'metalloid' },
  { name: 'Arsenic', atomicNumber: 33, symbol: 'As', atomicMass: 74.922, group: 15, period: 4, category: 'metalloid' },
  { name: 'Selenium', atomicNumber: 34, symbol: 'Se', atomicMass: 78.971, group: 16, period: 4, category: 'reactive-nonmetal' },
  { name: 'Bromine', atomicNumber: 35, symbol: 'Br', atomicMass: 79.904, group: 17, period: 4, category: 'reactive-nonmetal' },
  { name: 'Krypton', atomicNumber: 36, symbol: 'Kr', atomicMass: 83.798, group: 18, period: 4, category: 'noble-gas' },
  { name: 'Rubidium', atomicNumber: 37, symbol: 'Rb', atomicMass: 85.468, group: 1, period: 5, category: 'alkali-metal' },
  { name: 'Strontium', atomicNumber: 38, symbol: 'Sr', atomicMass: 87.62, group: 2, period: 5, category: 'alkaline-earth-metal' },
  { name: 'Yttrium', atomicNumber: 39, symbol: 'Y', atomicMass: 88.906, group: 3, period: 5, category: 'transition-metal' },
  { name: 'Zirconium', atomicNumber: 40, symbol: 'Zr', atomicMass: 91.224, group: 4, period: 5, category: 'transition-metal' },
  { name: 'Niobium', atomicNumber: 41, symbol: 'Nb', atomicMass: 92.906, group: 5, period: 5, category: 'transition-metal' },
  { name: 'Molybdenum', atomicNumber: 42, symbol: 'Mo', atomicMass: 95.96, group: 6, period: 5, category: 'transition-metal' },
  { name: 'Technetium', atomicNumber: 43, symbol: 'Tc', atomicMass: 98, group: 7, period: 5, category: 'transition-metal' },
  { name: 'Ruthenium', atomicNumber: 44, symbol: 'Ru', atomicMass: 101.07, group: 8, period: 5, category: 'transition-metal' },
  { name: 'Rhodium', atomicNumber: 45, symbol: 'Rh', atomicMass: 102.91, group: 9, period: 5, category: 'transition-metal' },
  { name: 'Palladium', atomicNumber: 46, symbol: 'Pd', atomicMass: 106.42, group: 10, period: 5, category: 'transition-metal' },
  { name: 'Silver', atomicNumber: 47, symbol: 'Ag', atomicMass: 107.87, group: 11, period: 5, category: 'transition-metal' },
  { name: 'Cadmium', atomicNumber: 48, symbol: 'Cd', atomicMass: 112.41, group: 12, period: 5, category: 'transition-metal' },
  { name: 'Indium', atomicNumber: 49, symbol: 'In', atomicMass: 114.82, group: 13, period: 5, category: 'post-transition-metal' },
  { name: 'Tin', atomicNumber: 50, symbol: 'Sn', atomicMass: 118.71, group: 14, period: 5, category: 'post-transition-metal' },
  { name: 'Antimony', atomicNumber: 51, symbol: 'Sb', atomicMass: 121.76, group: 15, period: 5, category: 'metalloid' },
  { name: 'Tellurium', atomicNumber: 52, symbol: 'Te', atomicMass: 127.60, group: 16, period: 5, category: 'metalloid' },
  { name: 'Iodine', atomicNumber: 53, symbol: 'I', atomicMass: 126.90, group: 17, period: 5, category: 'reactive-nonmetal' },
  { name: 'Xenon', atomicNumber: 54, symbol: 'Xe', atomicMass: 131.29, group: 18, period: 5, category: 'noble-gas' },
  { name: 'Caesium', atomicNumber: 55, symbol: 'Cs', atomicMass: 132.91, group: 1, period: 6, category: 'alkali-metal' },
  { name: 'Barium', atomicNumber: 56, symbol: 'Ba', atomicMass: 137.33, group: 2, period: 6, category: 'alkaline-earth-metal' },
  { name: 'Lanthanum', atomicNumber: 57, symbol: 'La', atomicMass: 138.91, group: 3, period: 8, category: 'lanthanide' },
  { name: 'Cerium', atomicNumber: 58, symbol: 'Ce', atomicMass: 140.12, group: 4, period: 8, category: 'lanthanide' },
  { name: 'Praseodymium', atomicNumber: 59, symbol: 'Pr', atomicMass: 140.91, group: 5, period: 8, category: 'lanthanide' },
  { name: 'Neodymium', atomicNumber: 60, symbol: 'Nd', atomicMass: 144.24, group: 6, period: 8, category: 'lanthanide' },
  { name: 'Promethium', atomicNumber: 61, symbol: 'Pm', atomicMass: 145, group: 7, period: 8, category: 'lanthanide' },
  { name: 'Samarium', atomicNumber: 62, symbol: 'Sm', atomicMass: 150.36, group: 8, period: 8, category: 'lanthanide' },
  { name: 'Europium', atomicNumber: 63, symbol: 'Eu', atomicMass: 151.96, group: 9, period: 8, category: 'lanthanide' },
  { name: 'Gadolinium', atomicNumber: 64, symbol: 'Gd', atomicMass: 157.25, group: 10, period: 8, category: 'lanthanide' },
  { name: 'Terbium', atomicNumber: 65, symbol: 'Tb', atomicMass: 158.93, group: 11, period: 8, category: 'lanthanide' },
  { name: 'Dysprosium', atomicNumber: 66, symbol: 'Dy', atomicMass: 162.50, group: 12, period: 8, category: 'lanthanide' },
  { name: 'Holmium', atomicNumber: 67, symbol: 'Ho', atomicMass: 164.93, group: 13, period: 8, category: 'lanthanide' },
  { name: 'Erbium', atomicNumber: 68, symbol: 'Er', atomicMass: 167.26, group: 14, period: 8, category: 'lanthanide' },
  { name: 'Thulium', atomicNumber: 69, symbol: 'Tm', atomicMass: 168.93, group: 15, period: 8, category: 'lanthanide' },
  { name: 'Ytterbium', atomicNumber: 70, symbol: 'Yb', atomicMass: 173.05, group: 16, period: 8, category: 'lanthanide' },
  { name: 'Lutetium', atomicNumber: 71, symbol: 'Lu', atomicMass: 174.97, group: 17, period: 8, category: 'lanthanide' },
  { name: 'Hafnium', atomicNumber: 72, symbol: 'Hf', atomicMass: 178.49, group: 4, period: 6, category: 'transition-metal' },
  { name: 'Tantalum', atomicNumber: 73, symbol: 'Ta', atomicMass: 180.95, group: 5, period: 6, category: 'transition-metal' },
  { name: 'Tungsten', atomicNumber: 74, symbol: 'W', atomicMass: 183.84, group: 6, period: 6, category: 'transition-metal' },
  { name: 'Rhenium', atomicNumber: 75, symbol: 'Re', atomicMass: 186.21, group: 7, period: 6, category: 'transition-metal' },
  { name: 'Osmium', atomicNumber: 76, symbol: 'Os', atomicMass: 190.23, group: 8, period: 6, category: 'transition-metal' },
  { name: 'Iridium', atomicNumber: 77, symbol: 'Ir', atomicMass: 192.22, group: 9, period: 6, category: 'transition-metal' },
  { name: 'Platinum', atomicNumber: 78, symbol: 'Pt', atomicMass: 195.08, group: 10, period: 6, category: 'transition-metal' },
  { name: 'Gold', atomicNumber: 79, symbol: 'Au', atomicMass: 196.97, group: 11, period: 6, category: 'transition-metal' },
  { name: 'Mercury', atomicNumber: 80, symbol: 'Hg', atomicMass: 200.59, group: 12, period: 6, category: 'transition-metal' },
  { name: 'Thallium', atomicNumber: 81, symbol: 'Tl', atomicMass: 204.38, group: 13, period: 6, category: 'post-transition-metal' },
  { name: 'Lead', atomicNumber: 82, symbol: 'Pb', atomicMass: 207.2, group: 14, period: 6, category: 'post-transition-metal' },
  { name: 'Bismuth', atomicNumber: 83, symbol: 'Bi', atomicMass: 208.98, group: 15, period: 6, category: 'post-transition-metal' },
  { name: 'Polonium', atomicNumber: 84, symbol: 'Po', atomicMass: 209, group: 16, period: 6, category: 'post-transition-metal' },
  { name: 'Astatine', atomicNumber: 85, symbol: 'At', atomicMass: 210, group: 17, period: 6, category: 'metalloid' },
  { name: 'Radon', atomicNumber: 86, symbol: 'Rn', atomicMass: 222, group: 18, period: 6, category: 'noble-gas' },
  { name: 'Francium', atomicNumber: 87, symbol: 'Fr', atomicMass: 223, group: 1, period: 7, category: 'alkali-metal' },
  { name: 'Radium', atomicNumber: 88, symbol: 'Ra', atomicMass: 226, group: 2, period: 7, category: 'alkaline-earth-metal' },
  { name: 'Actinium', atomicNumber: 89, symbol: 'Ac', atomicMass: 227, group: 3, period: 9, category: 'actinide' },
  { name: 'Thorium', atomicNumber: 90, symbol: 'Th', atomicMass: 232.04, group: 4, period: 9, category: 'actinide' },
  { name: 'Protactinium', atomicNumber: 91, symbol: 'Pa', atomicMass: 231.04, group: 5, period: 9, category: 'actinide' },
  { name: 'Uranium', atomicNumber: 92, symbol: 'U', atomicMass: 238.03, group: 6, period: 9, category: 'actinide' },
  { name: 'Neptunium', atomicNumber: 93, symbol: 'Np', atomicMass: 237, group: 7, period: 9, category: 'actinide' },
  { name: 'Plutonium', atomicNumber: 94, symbol: 'Pu', atomicMass: 244, group: 8, period: 9, category: 'actinide' },
  { name: 'Americium', atomicNumber: 95, symbol: 'Am', atomicMass: 243, group: 9, period: 9, category: 'actinide' },
  { name: 'Curium', atomicNumber: 96, symbol: 'Cm', atomicMass: 247, group: 10, period: 9, category: 'actinide' },
  { name: 'Berkelium', atomicNumber: 97, symbol: 'Bk', atomicMass: 247, group: 11, period: 9, category: 'actinide' },
  { name: 'Californium', atomicNumber: 98, symbol: 'Cf', atomicMass: 251, group: 12, period: 9, category: 'actinide' },
  { name: 'Einsteinium', atomicNumber: 99, symbol: 'Es', atomicMass: 252, group: 13, period: 9, category: 'actinide' },
  { name: 'Fermium', atomicNumber: 100, symbol: 'Fm', atomicMass: 257, group: 14, period: 9, category: 'actinide' },
  { name: 'Mendelevium', atomicNumber: 101, symbol: 'Md', atomicMass: 258, group: 15, period: 9, category: 'actinide' },
  { name: 'Nobelium', atomicNumber: 102, symbol: 'No', atomicMass: 259, group: 16, period: 9, category: 'actinide' },
  { name: 'Lawrencium', atomicNumber: 103, symbol: 'Lr', atomicMass: 262, group: 17, period: 9, category: 'actinide' },
  { name: 'Rutherfordium', atomicNumber: 104, symbol: 'Rf', atomicMass: 267, group: 4, period: 7, category: 'transition-metal' },
  { name: 'Dubnium', atomicNumber: 105, symbol: 'Db', atomicMass: 268, group: 5, period: 7, category: 'transition-metal' },
  { name: 'Seaborgium', atomicNumber: 106, symbol: 'Sg', atomicMass: 269, group: 6, period: 7, category: 'transition-metal' },
  { name: 'Bohrium', atomicNumber: 107, symbol: 'Bh', atomicMass: 270, group: 7, period: 7, category: 'transition-metal' },
  { name: 'Hassium', atomicNumber: 108, symbol: 'Hs', atomicMass: 277, group: 8, period: 7, category: 'transition-metal' },
  { name: 'Meitnerium', atomicNumber: 109, symbol: 'Mt', atomicMass: 278, group: 9, period: 7, category: 'unknown' },
  { name: 'Darmstadtium', atomicNumber: 110, symbol: 'Ds', atomicMass: 281, group: 10, period: 7, category: 'unknown' },
  { name: 'Roentgenium', atomicNumber: 111, symbol: 'Rg', atomicMass: 282, group: 11, period: 7, category: 'unknown' },
  { name: 'Copernicium', atomicNumber: 112, symbol: 'Cn', atomicMass: 285, group: 12, period: 7, category: 'transition-metal' },
  { name: 'Nihonium', atomicNumber: 113, symbol: 'Nh', atomicMass: 286, group: 13, period: 7, category: 'unknown' },
  { name: 'Flerovium', atomicNumber: 114, symbol: 'Fl', atomicMass: 289, group: 14, period: 7, category: 'post-transition-metal' },
  { name: 'Moscovium', atomicNumber: 115, symbol: 'Mc', atomicMass: 290, group: 15, period: 7, category: 'unknown' },
  { name: 'Livermorium', atomicNumber: 116, symbol: 'Lv', atomicMass: 293, group: 16, period: 7, category: 'unknown' },
  { name: 'Tennessine', atomicNumber: 117, symbol: 'Ts', atomicMass: 294, group: 17, period: 7, category: 'unknown' },
  { name: 'Oganesson', atomicNumber: 118, symbol: 'Og', atomicMass: 294, group: 18, period: 7, category: 'unknown' },
];
