
export type ElementData = {
  name: string;
  atomicNumber: number;
  symbol: string;
  group: number;
  period: number;
  category: 'alkali-metal' | 'alkaline-earth-metal' | 'lanthanide' | 'actinide' | 'transition-metal' | 'post-transition-metal' | 'metalloid' | 'reactive-nonmetal' | 'noble-gas' | 'unknown';
};

export const elements: ElementData[] = [
  { name: 'Hydrogen', atomicNumber: 1, symbol: 'H', group: 1, period: 1, category: 'reactive-nonmetal' },
  { name: 'Helium', atomicNumber: 2, symbol: 'He', group: 18, period: 1, category: 'noble-gas' },
  { name: 'Lithium', atomicNumber: 3, symbol: 'Li', group: 1, period: 2, category: 'alkali-metal' },
  { name: 'Beryllium', atomicNumber: 4, symbol: 'Be', group: 2, period: 2, category: 'alkaline-earth-metal' },
  { name: 'Boron', atomicNumber: 5, symbol: 'B', group: 13, period: 2, category: 'metalloid' },
  { name: 'Carbon', atomicNumber: 6, symbol: 'C', group: 14, period: 2, category: 'reactive-nonmetal' },
  { name: 'Nitrogen', atomicNumber: 7, symbol: 'N', group: 15, period: 2, category: 'reactive-nonmetal' },
  { name: 'Oxygen', atomicNumber: 8, symbol: 'O', group: 16, period: 2, category: 'reactive-nonmetal' },
  { name: 'Fluorine', atomicNumber: 9, symbol: 'F', group: 17, period: 2, category: 'reactive-nonmetal' },
  { name: 'Neon', atomicNumber: 10, symbol: 'Ne', group: 18, period: 2, category: 'noble-gas' },
  { name: 'Sodium', atomicNumber: 11, symbol: 'Na', group: 1, period: 3, category: 'alkali-metal' },
  { name: 'Magnesium', atomicNumber: 12, symbol: 'Mg', group: 2, period: 3, category: 'alkaline-earth-metal' },
  { name: 'Aluminium', atomicNumber: 13, symbol: 'Al', group: 13, period: 3, category: 'post-transition-metal' },
  { name: 'Silicon', atomicNumber: 14, symbol: 'Si', group: 14, period: 3, category: 'metalloid' },
  { name: 'Phosphorus', atomicNumber: 15, symbol: 'P', group: 15, period: 3, category: 'reactive-nonmetal' },
  { name: 'Sulfur', atomicNumber: 16, symbol: 'S', group: 16, period: 3, category: 'reactive-nonmetal' },
  { name: 'Chlorine', atomicNumber: 17, symbol: 'Cl', group: 17, period: 3, category: 'reactive-nonmetal' },
  { name: 'Argon', atomicNumber: 18, symbol: 'Ar', group: 18, period: 3, category: 'noble-gas' },
  { name: 'Potassium', atomicNumber: 19, symbol: 'K', group: 1, period: 4, category: 'alkali-metal' },
  { name: 'Calcium', atomicNumber: 20, symbol: 'Ca', group: 2, period: 4, category: 'alkaline-earth-metal' },
  { name: 'Scandium', atomicNumber: 21, symbol: 'Sc', group: 3, period: 4, category: 'transition-metal' },
  { name: 'Titanium', atomicNumber: 22, symbol: 'Ti', group: 4, period: 4, category: 'transition-metal' },
  { name: 'Vanadium', atomicNumber: 23, symbol: 'V', group: 5, period: 4, category: 'transition-metal' },
  { name: 'Chromium', atomicNumber: 24, symbol: 'Cr', group: 6, period: 4, category: 'transition-metal' },
  { name: 'Manganese', atomicNumber: 25, symbol: 'Mn', group: 7, period: 4, category: 'transition-metal' },
  { name: 'Iron', atomicNumber: 26, symbol: 'Fe', group: 8, period: 4, category: 'transition-metal' },
  { name: 'Cobalt', atomicNumber: 27, symbol: 'Co', group: 9, period: 4, category: 'transition-metal' },
  { name: 'Nickel', atomicNumber: 28, symbol: 'Ni', group: 10, period: 4, category: 'transition-metal' },
  { name: 'Copper', atomicNumber: 29, symbol: 'Cu', group: 11, period: 4, category: 'transition-metal' },
  { name: 'Zinc', atomicNumber: 30, symbol: 'Zn', group: 12, period: 4, category: 'transition-metal' },
  { name: 'Gallium', atomicNumber: 31, symbol: 'Ga', group: 13, period: 4, category: 'post-transition-metal' },
  { name: 'Germanium', atomicNumber: 32, symbol: 'Ge', group: 14, period: 4, category: 'metalloid' },
  { name: 'Arsenic', atomicNumber: 33, symbol: 'As', group: 15, period: 4, category: 'metalloid' },
  { name: 'Selenium', atomicNumber: 34, symbol: 'Se', group: 16, period: 4, category: 'reactive-nonmetal' },
  { name: 'Bromine', atomicNumber: 35, symbol: 'Br', group: 17, period: 4, category: 'reactive-nonmetal' },
  { name: 'Krypton', atomicNumber: 36, symbol: 'Kr', group: 18, period: 4, category: 'noble-gas' },
  { name: 'Rubidium', atomicNumber: 37, symbol: 'Rb', group: 1, period: 5, category: 'alkali-metal' },
  { name: 'Strontium', atomicNumber: 38, symbol: 'Sr', group: 2, period: 5, category: 'alkaline-earth-metal' },
  { name: 'Yttrium', atomicNumber: 39, symbol: 'Y', group: 3, period: 5, category: 'transition-metal' },
  { name: 'Zirconium', atomicNumber: 40, symbol: 'Zr', group: 4, period: 5, category: 'transition-metal' },
  { name: 'Niobium', atomicNumber: 41, symbol: 'Nb', group: 5, period: 5, category: 'transition-metal' },
  { name: 'Molybdenum', atomicNumber: 42, symbol: 'Mo', group: 6, period: 5, category: 'transition-metal' },
  { name: 'Technetium', atomicNumber: 43, symbol: 'Tc', group: 7, period: 5, category: 'transition-metal' },
  { name: 'Ruthenium', atomicNumber: 44, symbol: 'Ru', group: 8, period: 5, category: 'transition-metal' },
  { name: 'Rhodium', atomicNumber: 45, symbol: 'Rh', group: 9, period: 5, category: 'transition-metal' },
  { name: 'Palladium', atomicNumber: 46, symbol: 'Pd', group: 10, period: 5, category: 'transition-metal' },
  { name: 'Silver', atomicNumber: 47, symbol: 'Ag', group: 11, period: 5, category: 'transition-metal' },
  { name: 'Cadmium', atomicNumber: 48, symbol: 'Cd', group: 12, period: 5, category: 'transition-metal' },
  { name: 'Indium', atomicNumber: 49, symbol: 'In', group: 13, period: 5, category: 'post-transition-metal' },
  { name: 'Tin', atomicNumber: 50, symbol: 'Sn', group: 14, period: 5, category: 'post-transition-metal' },
  { name: 'Antimony', atomicNumber: 51, symbol: 'Sb', group: 15, period: 5, category: 'metalloid' },
  { name: 'Tellurium', atomicNumber: 52, symbol: 'Te', group: 16, period: 5, category: 'metalloid' },
  { name: 'Iodine', atomicNumber: 53, symbol: 'I', group: 17, period: 5, category: 'reactive-nonmetal' },
  { name: 'Xenon', atomicNumber: 54, symbol: 'Xe', group: 18, period: 5, category: 'noble-gas' },
  { name: 'Caesium', atomicNumber: 55, symbol: 'Cs', group: 1, period: 6, category: 'alkali-metal' },
  { name: 'Barium', atomicNumber: 56, symbol: 'Ba', group: 2, period: 6, category: 'alkaline-earth-metal' },
  { name: 'Lanthanum', atomicNumber: 57, symbol: 'La', group: 3, period: 8, category: 'lanthanide' },
  { name: 'Cerium', atomicNumber: 58, symbol: 'Ce', group: 4, period: 8, category: 'lanthanide' },
  { name: 'Praseodymium', atomicNumber: 59, symbol: 'Pr', group: 5, period: 8, category: 'lanthanide' },
  { name: 'Neodymium', atomicNumber: 60, symbol: 'Nd', group: 6, period: 8, category: 'lanthanide' },
  { name: 'Promethium', atomicNumber: 61, symbol: 'Pm', group: 7, period: 8, category: 'lanthanide' },
  { name: 'Samarium', atomicNumber: 62, symbol: 'Sm', group: 8, period: 8, category: 'lanthanide' },
  { name: 'Europium', atomicNumber: 63, symbol: 'Eu', group: 9, period: 8, category: 'lanthanide' },
  { name: 'Gadolinium', atomicNumber: 64, symbol: 'Gd', group: 10, period: 8, category: 'lanthanide' },
  { name: 'Terbium', atomicNumber: 65, symbol: 'Tb', group: 11, period: 8, category: 'lanthanide' },
  { name: 'Dysprosium', atomicNumber: 66, symbol: 'Dy', group: 12, period: 8, category: 'lanthanide' },
  { name: 'Holmium', atomicNumber: 67, symbol: 'Ho', group: 13, period: 8, category: 'lanthanide' },
  { name: 'Erbium', atomicNumber: 68, symbol: 'Er', group: 14, period: 8, category: 'lanthanide' },
  { name: 'Thulium', atomicNumber: 69, symbol: 'Tm', group: 15, period: 8, category: 'lanthanide' },
  { name: 'Ytterbium', atomicNumber: 70, symbol: 'Yb', group: 16, period: 8, category: 'lanthanide' },
  { name: 'Lutetium', atomicNumber: 71, symbol: 'Lu', group: 17, period: 8, category: 'lanthanide' },
  { name: 'Hafnium', atomicNumber: 72, symbol: 'Hf', group: 4, period: 6, category: 'transition-metal' },
  { name: 'Tantalum', atomicNumber: 73, symbol: 'Ta', group: 5, period: 6, category: 'transition-metal' },
  { name: 'Tungsten', atomicNumber: 74, symbol: 'W', group: 6, period: 6, category: 'transition-metal' },
  { name: 'Rhenium', atomicNumber: 75, symbol: 'Re', group: 7, period: 6, category: 'transition-metal' },
  { name: 'Osmium', atomicNumber: 76, symbol: 'Os', group: 8, period: 6, category: 'transition-metal' },
  { name: 'Iridium', atomicNumber: 77, symbol: 'Ir', group: 9, period: 6, category: 'transition-metal' },
  { name: 'Platinum', atomicNumber: 78, symbol: 'Pt', group: 10, period: 6, category: 'transition-metal' },
  { name: 'Gold', atomicNumber: 79, symbol: 'Au', group: 11, period: 6, category: 'transition-metal' },
  { name: 'Mercury', atomicNumber: 80, symbol: 'Hg', group: 12, period: 6, category: 'transition-metal' },
  { name: 'Thallium', atomicNumber: 81, symbol: 'Tl', group: 13, period: 6, category: 'post-transition-metal' },
  { name: 'Lead', atomicNumber: 82, symbol: 'Pb', group: 14, period: 6, category: 'post-transition-metal' },
  { name: 'Bismuth', atomicNumber: 83, symbol: 'Bi', group: 15, period: 6, category: 'post-transition-metal' },
  { name: 'Polonium', atomicNumber: 84, symbol: 'Po', group: 16, period: 6, category: 'post-transition-metal' },
  { name: 'Astatine', atomicNumber: 85, symbol: 'At', group: 17, period: 6, category: 'metalloid' },
  { name: 'Radon', atomicNumber: 86, symbol: 'Rn', group: 18, period: 6, category: 'noble-gas' },
  { name: 'Francium', atomicNumber: 87, symbol: 'Fr', group: 1, period: 7, category: 'alkali-metal' },
  { name: 'Radium', atomicNumber: 88, symbol: 'Ra', group: 2, period: 7, category: 'alkaline-earth-metal' },
  { name: 'Actinium', atomicNumber: 89, symbol: 'Ac', group: 3, period: 9, category: 'actinide' },
  { name: 'Thorium', atomicNumber: 90, symbol: 'Th', group: 4, period: 9, category: 'actinide' },
  { name: 'Protactinium', atomicNumber: 91, symbol: 'Pa', group: 5, period: 9, category: 'actinide' },
  { name: 'Uranium', atomicNumber: 92, symbol: 'U', group: 6, period: 9, category: 'actinide' },
  { name: 'Neptunium', atomicNumber: 93, symbol: 'Np', group: 7, period: 9, category: 'actinide' },
  { name: 'Plutonium', atomicNumber: 94, symbol: 'Pu', group: 8, period: 9, category: 'actinide' },
  { name: 'Americium', atomicNumber: 95, symbol: 'Am', group: 9, period: 9, category: 'actinide' },
  { name: 'Curium', atomicNumber: 96, symbol: 'Cm', group: 10, period: 9, category: 'actinide' },
  { name: 'Berkelium', atomicNumber: 97, symbol: 'Bk', group: 11, period: 9, category: 'actinide' },
  { name: 'Californium', atomicNumber: 98, symbol: 'Cf', group: 12, period: 9, category: 'actinide' },
  { name: 'Einsteinium', atomicNumber: 99, symbol: 'Es', group: 13, period: 9, category: 'actinide' },
  { name: 'Fermium', atomicNumber: 100, symbol: 'Fm', group: 14, period: 9, category: 'actinide' },
  { name: 'Mendelevium', atomicNumber: 101, symbol: 'Md', group: 15, period: 9, category: 'actinide' },
  { name: 'Nobelium', atomicNumber: 102, symbol: 'No', group: 16, period: 9, category: 'actinide' },
  { name: 'Lawrencium', atomicNumber: 103, symbol: 'Lr', group: 17, period: 9, category: 'actinide' },
  { name: 'Rutherfordium', atomicNumber: 104, symbol: 'Rf', group: 4, period: 7, category: 'transition-metal' },
  { name: 'Dubnium', atomicNumber: 105, symbol: 'Db', group: 5, period: 7, category: 'transition-metal' },
  { name: 'Seaborgium', atomicNumber: 106, symbol: 'Sg', group: 6, period: 7, category: 'transition-metal' },
  { name: 'Bohrium', atomicNumber: 107, symbol: 'Bh', group: 7, period: 7, category: 'transition-metal' },
  { name: 'Hassium', atomicNumber: 108, symbol: 'Hs', group: 8, period: 7, category: 'transition-metal' },
  { name: 'Meitnerium', atomicNumber: 109, symbol: 'Mt', group: 9, period: 7, category: 'unknown' },
  { name: 'Darmstadtium', atomicNumber: 110, symbol: 'Ds', group: 10, period: 7, category: 'unknown' },
  { name: 'Roentgenium', atomicNumber: 111, symbol: 'Rg', group: 11, period: 7, category: 'unknown' },
  { name: 'Copernicium', atomicNumber: 112, symbol: 'Cn', group: 12, period: 7, category: 'transition-metal' },
  { name: 'Nihonium', atomicNumber: 113, symbol: 'Nh', group: 13, period: 7, category: 'unknown' },
  { name: 'Flerovium', atomicNumber: 114, symbol: 'Fl', group: 14, period: 7, category: 'post-transition-metal' },
  { name: 'Moscovium', atomicNumber: 115, symbol: 'Mc', group: 15, period: 7, category: 'unknown' },
  { name: 'Livermorium', atomicNumber: 116, symbol: 'Lv', group: 16, period: 7, category: 'unknown' },
  { name: 'Tennessine', atomicNumber: 117, symbol: 'Ts', group: 17, period: 7, category: 'unknown' },
  { name: 'Oganesson', atomicNumber: 118, symbol: 'Og', group: 18, period: 7, category: 'unknown' },
];

    